### ISSUE TITLE
CCIP Bombing.

### ISSUE THREAD

**Issue by AxelPaccalin** [5H1N0B11/flightgear-mirage2000#101]
- [ ] Implement CCIP algorithms & integrate them in the HUD.
- [ ] Integrate the bombs models. 
- [ ] Update selection & release mechanism.

-------

List of bombs using CCIP:
- SAMP Mk-82
- SAMP Mk-82 Snake-Eye
- BLG-66

**Comment by AxelPaccalin** [comment]
@5H1N0B11, do you have doc on the real m2000-5 CCIP consoles & HUD ? Or should we use those of DCS (m2000C) ?
DCS HUD:
![CCIP-HUD-DCS](https://user-images.githubusercontent.com/47812280/89533554-e22f5900-d7f3-11ea-8460-ad7c70c8a1f3.PNG)
DCS Console:
![CCIP-Console-DCS](https://user-images.githubusercontent.com/47812280/89533591-f1160b80-d7f3-11ea-80cb-3027e0e0e744.PNG)

**Comment by vanosten** [comment]
IMO if there is no Mirage 2000-5 docs, then it should be based on 2000-C docs instead of DCS

**Comment by Rudolf339** [comment]
SAMP Mk-82 and SAMP Mk-82 Snake-Eye are implemented and droppable on my fork ( [](https://github.com/Rudolf339/Aircraft/tree/weapons)
They need some fine tuning for the animations, the drag fins and the fuze propellers don't yet move. I think for the 2000-5 these and maybe the BLG-66 cluster bomb are enough, the rest can be added when we have a dedicated Mirage 2000D

**Comment by AxelPaccalin** [comment]
Okay, is the branch ready for merge ?

**Comment by NikolaiVChr** [comment]
Missile-code already has CCIP and CCRP methods you can just call, all you need to do is show it in the HUD more or less.
Why do you want to make new ones, did you find flaws in the existing ones?

**Comment by paccalin** [comment]
@Rudolf339 Asked me to do so and I didn't find these untill today actually. I guess I can use them for the HUD instead indeed. But I still need a free-fall object for testing. 
They are used for the current LGB implementation, right ?

**Comment by 5H1N0B11** [comment]
Well. While waiting it you could take a gun that you painted in red, make it one of the bomb the f16 can take, take the "load" config in the f16 and you have a free fall object that you could use to test it.

**Comment by 5H1N0B11** [comment]
the CCIP is now done on the mirage. I could close this issue, but there is still some load to add. (BLG-66)

**Comment by vanosten** [comment]
The CCIP is only available when MP messaging is off. When MP messaging is on, then it is not shown.

**Comment by vanosten** [comment]
I cannot replicate anymore what I found a few hours ago. I cannot get it to show.

**Comment by vanosten** [comment]
![fgfs-20240915100657](https://github.com/user-attachments/assets/3c78fadd-faee-4d8b-89e0-157348f0a770)

Damage on. So my conclusion on Windows 10 and FG NEXT is that CCIP works. You have to be fast enough and high enough to make it show up. IMO this issue should be closed.

**Comment by vanosten** [comment]
CCIP works with today's merge. Uses code in missil-code.nas
