### ISSUE TITLE
CCRP Bombing.

### ISSUE THREAD

**Issue by AxelPaccalin** [5H1N0B11/flightgear-mirage2000#102]
- [ ] Implement CCRP algorithms & integrate them in the HUD.
- [ ] Integrate the bombs models. 
- [ ] Update selection & release mechanism.

-------

List of bombs using CCRP:
- TODO

**Comment by AxelPaccalin** [comment]
CCRP algorithms will probably depend on CCIP algorithms (see #101).

**Comment by 5H1N0B11** [comment]
CCRP is nearly done. only the target on ground should be displayed as a cross and not as a square (that's on going)

**Comment by vanosten** [comment]
As per today's merge this works. Uses missile-code.nas CCRP code
