### ISSUE TITLE
Remove ok buttons etc. from dialogues in Mirage 2000 menu

### ISSUE THREAD

**Issue by vanosten** [5H1N0B11/flightgear-mirage2000#125]
Most buttons at the bottom of the dialogue screens in the Mirage 2000 menu do nothing and there is no consistency. E.g.:

- Configuration: nothing happens, when the "Ok" button is pressed - not even closing the window. There is no need for the button. The window can be closed by the usual upper right window button in FG.
- Lighting & Radar: no need for a "Close" button
- Options: I have never found out what the 2 button at the bottom are supposed to do. they do not seem to have an effect.

**Comment by paccalin** [comment]
I'm willing to remove these, but before doing anything, anyone would know about the buttons in the option dialog ?

**Comment by 5H1N0B11** [comment]
This is true. I will remove useless button. But even more, we need to think about what we want in GUI, in order to avoid "5H1N0BI's is alone and doing test with menu" to provide a user friendly GUI. I may let this issue open, even if the useless button are removed

**Comment by 5H1N0B11** [comment]
I think this is done now. closing the issue
