### ISSUE TITLE
Ships are often not detected

### ISSUE THREAD

**Issue by vanosten** [5H1N0B11/flightgear-mirage2000#126]
In Hunter ships are often not detected. In the attached screenshots (all within the same Hunter session and mostly the same ships) they are detected if MP if off and not detected if MP is on.

There seems to be no difference in which type of ship it is (OPRF asset missile-frigate or Leto's ships) and no difference which radar mode. All ships are detected just fine with the Viggen.

**Comment by vanosten** [comment]
![fgfs-20201010103450](https://user-images.githubusercontent.com/245995/95653314-1ecf4780-0af8-11eb-8953-64477c25f7a7.png)
![fgfs-20201010103639](https://user-images.githubusercontent.com/245995/95653315-20990b00-0af8-11eb-80dd-8da47355cdb3.png)
![fgfs-20201010103646](https://user-images.githubusercontent.com/245995/95653316-2131a180-0af8-11eb-805c-9750cc7528fd.png)
![fgfs-20201010104042](https://user-images.githubusercontent.com/245995/95653317-21ca3800-0af8-11eb-97ab-26737f557cfe.png)
![fgfs-20201010104146](https://user-images.githubusercontent.com/245995/95653318-2262ce80-0af8-11eb-86ff-83883bef7a0c.png)
![fgfs-20201010104537](https://user-images.githubusercontent.com/245995/95653319-2393fb80-0af8-11eb-914a-d1e2eebe0c54.png)
![fgfs-20201010104655](https://user-images.githubusercontent.com/245995/95653320-242c9200-0af8-11eb-8381-477dd26e4f96.png)
![fgfs-20201010104841](https://user-images.githubusercontent.com/245995/95653321-24c52880-0af8-11eb-82f4-8d75a88fb05a.png)
![fgfs-20201010104845](https://user-images.githubusercontent.com/245995/95653322-25f65580-0af8-11eb-8aed-efa402c7abfd.png)
![fgfs-20201010105300](https://user-images.githubusercontent.com/245995/95653323-268eec00-0af8-11eb-9557-7e392cc56585.png)

**Comment by vanosten** [comment]
Branch CanvasRadarPrototype picks up in many cases, but not reliably (lock gets lost)

**Comment by 5H1N0B11** [comment]
I think this is related to the get_type issue I worked on recently. I'm testing if alt <100 and if the ai model is in a hash that contains the name of the models (it was made when we had few sea models). So I don't know what should we do. Maybe sharing a list of every boat models. Or using an other way to detect an object that is on water <- this is the real challenge : an object on ground wont be detect (due to doppler), but I need to differentiate ground to water in order to make the difference.

**Comment by 5H1N0B11** [comment]
So thanks to @NikolaiVChr help on this one, I made the correction and it is working very well : looking at the terrain under the target and see if it is ground or water. I'll close  the issue.
