### ISSUE TITLE
MP Targets Won't Lock

### ISSUE THREAD

**Issue by niallsalmon** [5H1N0B11/flightgear-mirage2000#129]
So @R41NB0WTH3R41NW1NG and I were trying to shoot down the automats at KXTA and well anyways our radars couldn't lock on to the automats. It locks on ai objects though (tankers for example) so well anyways there is an issue with that. I assume the new radar will fix it but I will submit an issue regardless.

**Comment by 5H1N0B11** [comment]
so now I can lock and shoot automat with the new version. Could you try and tel me if this is working ?
