### ISSUE TITLE
Emesary

### ISSUE THREAD

**Issue by 5H1N0B11** [5H1N0B11/flightgear-mirage2000#142]
We have to switch to Emesary

**Comment by 5H1N0B11** [comment]
I got an error. I need to investigate later today.
`  255.16 [ALRT]:nasal      Nasal runtime error: Failed to add command:emesary-transmit : likely a duplicate name 
  255.16 [ALRT]:nasal        at /media/Data/Jeux/Jeux/Workshop/flightgear-mirage2000/Mirage-2000/Nasal/emesary.nas, line 707
  255.16 [ALRT]:nasal      Cannot find Nasal script 'Aircraft/Mirage-2000/Nasal/M_frame_notification.nas' for module 'notifications'.
`

**Comment by NikolaiVChr** [comment]
M_frame_notification.nas is something f16 uses, I dont think you need that.

The other error, is because you have 2 files loaded you should not have, read the bottom of this page:
https://github.com/NikolaiVChr/OpRedFlag/blob/master/emesary-damage-system/how-to-install.txt

**Comment by 5H1N0B11** [comment]
Indeed. Problem solved. Thanks
