### ISSUE TITLE
Speed Brakes rework 

### ISSUE THREAD

**Issue by niallsalmon** [5H1N0B11/flightgear-mirage2000#157]
Make speed brakes deploy during gear down by simply pressing b and while we are at it can employ in/out button (usually j/k by default)

**Comment by 5H1N0B11** [comment]
it is working with CTRL-b

**Comment by 5H1N0B11** [comment]
Btw they should be a bit faster to move. We need to find where it is done on the file : They are actually too slow to deploy. From what I have seen, it seems that they should be fully deployed more or less in 1 second. This is not the case actually

**Comment by 5H1N0B11** [comment]
I think this is ok. I will close it.
