### ISSUE TITLE
slats and airbrake instruments

### ISSUE THREAD

**Issue by hardba11** [5H1N0B11/flightgear-mirage2000#169]
animation of slats and airbrake position on instruments does not work anymore

as theese instruments are fake (not present in the real mirage 2000 cockpit) it could be deleted

**Comment by 5H1N0B11** [comment]
Indeed. These instrument were made in a time when the real instrument wasn't modeled. As we have a wonderful AF and aoa indicator on HUD we can remove them.

**Comment by 5H1N0B11** [comment]
I have disabled it from now and they wont be loaded. If we keep it like that,once, we should deleted the xml.
