### ISSUE TITLE
Sorting out liveries. 

### ISSUE THREAD

**Issue by niallsalmon** [5H1N0B11/flightgear-mirage2000#170]
I propose a new form of sorting liveries png's, per variant, like how the f16 has different folders of liveries for different blocks. 

For the mirage 2000 -5/-5B:
- 100 years lafayette
- Corse
- Sky Blue
- sand
- egypt
- peru 1
- peru 2
- qatar
and all of the png in 1024x1024 (im lazy to list, sorry)

For the Mirage 2000D/N
- Ouadi Doum
- Desert
- 2000D
- 2000N

Also, i think we should do the logos as well, though I don't know where goes where so may I ask @R41NB0WTH3R41NW1NG to help me? 

If I missed anything please let me know

- Salmon

**Comment by paccalin** [comment]
That's a very good idea!

How do you think we should handle fictionnal liveries?

**Comment by niallsalmon** [comment]
True, I am not sure. The other day in the server I thought of another way of doing it. I will keep the current layout but instead in the help menu or wherever, we can have a list of suggested realistic combinations. That still gives the user the freedom to mix around livs and logos.

**Comment by paccalin** [comment]
Yes, why not!
Just thought of something else, but I'm not really familiar with how xml is used for the menu, so I'm not 100% sure on how to implement it but here is an idea which I think mixes the best of both world:
 - we use an xml to define a list of realistic livs for the 2000 -5/-5B
 - we use another xml to define a list of realistic livs for the Mirage 2000D/N
 - we use a third xml to define a list of fictionnal livs.

Then when comes the time to create the menu, we use either the first and third xml, or the second and third (depending on the aircraft variant selected).
Once again, I'm not sure what this implies to implement it that way, so it's mostly just an idea ^^

**Comment by R41NB0WTH3R41NW1NG** [comment]
Before this, I wanted to suggest you something. What if we made a canvas livery selector that used both liveries and logos at the same time to make the liveries, a bit like the payload selector on the MiG-21?
For example
-French Air Force
  > Classical liveries
    •EC1/2 "Cigognes" (Sky camo) 
    •EC1/12 [...]
  > Special liveries
    •Tigermeet 2014
    •Dissolution Escadron Normandie
    •[...]
-Indian Air Force
  •KT204 (Forest camo)
  •KF144 (Sky camo)
Etc. The air forces would be the root folders, eventual normal/special liveries as subfolders and the liveries inside this all. We could also leave a "fictional" livery folder, like an Air Force. Of course, the canvas dialog would change depending on the Mirage version. Please tell me about your thoughts on the matter, and if it would be possible. I will try to make this work, but I will give no promises as I am a complete beginner.

**Comment by paccalin** [comment]
> Before this, I wanted to suggest you something. What if we made a canvas livery selector that used both liveries and logos at the same time to make the liveries, a bit like the payload selector on the MiG-21?

This could be interesting but only as a standalone feature (not replacing the current modular livs/logo selection). 
Plus, I think this should be discussed in a new issue as this isn't directly related to this one!

**Comment by 5H1N0B11** [comment]
I would suggest to do some investigation in FG aircraft, especially airliner who have lot of liveries and see how it is managed (and we can find a cool menu and take it)

**Comment by niallsalmon** [comment]
I think we can close this now as well.
