### ISSUE TITLE
Logos do not work on the twin-seats

### ISSUE THREAD

**Issue by R41NB0WTH3R41NW1NG** [5H1N0B11/flightgear-mirage2000#172]
Logo 3d models do not follow the moving parts of the main model.

**Comment by R41NB0WTH3R41NW1NG** [comment]
They now move, but they do strange movements. Especially the logos on the rudder:
https://cdn.discordapp.com/attachments/413085065904390144/777516287605735434/FlightGear_2020-11-15_13-49-17.mp4

**Comment by 5H1N0B11** [comment]
Well it seems to be inverted ...

**Comment by R41NB0WTH3R41NW1NG** [comment]
> Well it seems to be inverted ...

Indeed. I would also say that the rotation amplitude is too strong: it should not be able to rotate 90°  on either side.

**Comment by 5H1N0B11** [comment]
Corrected
