### ISSUE TITLE
Help dialog too long

### ISSUE THREAD

**Issue by Renaud-Roquefort** [5H1N0B11/flightgear-mirage2000#181]
Would it be possible to port the F-16's help dialog template to the Mirage? It is too long at the moment and is larger than the screen can contain. Also, it would be useful to take a few things from the manual and put them there. I can take care of what is needed from it if you want.

**Comment by 5H1N0B11** [comment]
That could be great if you can indeed work on the help menu. Taking what is best on other aircraft and from your fligth manual.

**Comment by vanosten** [comment]
Do we really want this? I would rather have an updated manual and a pointer to it. Maybe converting the current beautiful manual to .md files and have them versioned like the F-16.

The F-16 way of doing things uses /Nasal/help.nas and /systems/f16-help.xml, which is referenced from /f16-base.xml

**Comment by vanosten** [comment]
Has been changed to a redirect to the wiki. Will over time instead have "all" key bindings in the aircraft help - instead of just an arbitrary selection.
