### ISSUE TITLE
Some armaments do not work with emesary

### ISSUE THREAD

**Issue by R41NB0WTH3R41NW1NG** [5H1N0B11/flightgear-mirage2000#185]
Guns can shoot but do not hit. Nothing appears on the logs. 
The Magic II seems to be broken as well. It does lock and it does shoot, but never follows the target; it seems to simply drift to the ground.

**Comment by 5H1N0B11** [comment]
It's working now. Gun need some testing and so deos the magic 2.

**Comment by 5H1N0B11** [comment]
I'll close this in 1 week if there is no feed back.

**Comment by R41NB0WTH3R41NW1NG** [comment]
Everything works, you can close the issue
