### ISSUE TITLE
Fallback models not working

### ISSUE THREAD

**Issue by colingeniet** [5H1N0B11/flightgear-mirage2000#186]
The fallback model set with `<fallback-model-index>` is not working (shows the default yellow/blue aircraft),
because the property was added under `/sim/`, whereas it should be under `/sim/model/`.

**Comment by 5H1N0B11** [comment]
It should be ok. some more test of the last version and I can close the topic

**Comment by Rudolf339** [comment]
this was fixed with #205 , this issue may be closed
