### ISSUE TITLE
Multiplayer range is set to 100, but it should be 160 at least.

### ISSUE THREAD

**Issue by Megaf** [5H1N0B11/flightgear-mirage2000#220]
Multiplayer range is set to 100, which is the FG's default. But it would be recommended to set it to 160 instead because that's the maximum radar range, since this is the radar range.

Multiplayer range can be set via the property `/sim/multiplay/visibility-range-nm` and setting it to `=160`.

The mp distance can be discussed because one thing is radar range, the other thing is radio range.

**Comment by 5H1N0B11** [comment]
@Megaf no other oprf aircraft are setting up this property : "mp-visibility-range"
and I don't think they should, as it is not an aircraft property but a FG intern property.
it means it will stay at 160 until another aircraft changes it or you do it manually.I will not do that

**Comment by Zaretto** [comment]
When I added this functionality to FlightGear it was with the intention that only the aircraft models would set it; and that the values used would be appropriate.

This value is not archived and will be set to 100 every time that FlightGear is started.

The F-15 sets this to 200 because that is a reasonable approximation of the maximum operating radar range although possibly in some circumstances high visibility targets could be visible further away.

**Comment by Megaf** [comment]
**Default range.**
If I am not mistaken, the default range for all aircraft in FG is 100 nm. And again, if I am not mistaken, this is initially set by the multiplayer server.

**The Issue**
The issue with having only 100 nmi for mp range, is that not only this range is smaller than what aircraft radar is capable, but it limits the distance we can chat with each other.

In addition to that, it limits the distance we can be aware of each other's presence in multiplayer. Often making it seems that our fight buddy is not online.

More often than not, in BVR training, my opponent thinks that either they are having connectivity issues or I am because we can't communicate in mp chat. Then we have to resort to other means of communication and manually set the mp visibility range.

**The Solution**
I genuinely believe that all our OPRF aircraft should set the range to 200 nm.

Not only this better reflects the radar capabilities, but it greatly facilitates training for Beyond Visual Range combats.

In my opinion, the hard limit for radar range should be given by the radar's capabilities and radar contact radar cross-section and not multiplayer visibility.

**Comment by Zaretto** [comment]
This issue was completed with 05497440ebb165b8b76465eba03e71ffa81f22fe where the range is set to 200 - discussion of OPRF policy and other aircraft is not appropriate on this issue.
