### ISSUE TITLE
Clarifications on blackout

### ISSUE THREAD

**Issue by Megaf** [5H1N0B11/flightgear-mirage2000#221]
The default for OPRF aircraft is starting blacking out at 5 G, but in the Mirage at 8G you still fine and see fine.

In this screenshot I'm pulling 6G
![image](https://user-images.githubusercontent.com/6201512/129453434-ccb20da8-9a45-46f1-bef6-bd6f33c24b29.png)
This is the F-14 nearly total blackout at 5.7 G
![image](https://user-images.githubusercontent.com/6201512/129453449-03c00f60-5c9c-4666-bacc-2846d530418f.png)

Wolf on Discord also reported:
> Just tested redout and blackout, it's correctly set in the cockpit view options, but blackout doesn't show up under 8G for some reason

**Comment by l0k1** [comment]
> The default for OPRF aircraft

OPRF has no default, so this is bad information, and aircraft should not be adjusted based on this.

**Comment by Zaretto** [comment]
The readout/blackout system in the Mirage is based on the excellent work of @NikolaiVChr - which in turn builds on solid research by Gerald J. Kron and Frank M. Cardullo (Singer Link Simulation Binghampton) for the F-16.

There are a number of factors that influence the blackout/redout simulation - it's not just the amount of G's being pulled; so different aircraft may produce different effects.

See 

* https://forum.flightgear.org/viewtopic.php?f=4&t=30985
* https://apps.dtic.mil/dtic/tr/fulltext/u2/a109127.pdf
* https://www.skybrary.aero/index.php/G-induced_Impairment_and_the_Risk_Of_G-LOC

Other reports

* https://www.atsb.gov.au/media/761497/g-induced_loss_of_consciousness.pdf
* https://web.archive.org/web/20200325081718/https://link.springer.com/content/pdf/10.1186%2F2046-7648-2-19.pdf

So currently this is something that I consider to be working as designed, unless you can provide some concrete data to show that this isn't working as designed.

Maybe we should check to ensure that OPRF aircraft are using the same parameters but this is more something for @l0k1 and @NikolaiVChr to decide.

**Comment by Megaf** [comment]
Closing this as I don't have enough evidence to suggest we have an issue.
