### ISSUE TITLE
Targets in Hub Swap Text

### ISSUE THREAD

**Issue by Minecraft-SMP** [5H1N0B11/flightgear-mirage2000#54]
I noticed that the targets in the hud are swaping the texts ( Name, Altitude, Speed) continuously when targets are close to each other.

**Comment by 5H1N0B11** [comment]
I think it still happen a bit, but lot less than before. Could someone confirm ?

**Comment by Adzorn** [comment]
Seems to be fixed, Haven't noticed this issue on the current build
