### ISSUE TITLE
Show in one of the MFDs whether true or magnetic heading is chosen

### ISSUE THREAD

**Issue by vanosten** [5H1N0B11/flightgear-mirage2000#71]
The second button from right below the center MFD allows to toggle between magnetic and geographic/true north. However there is no indication, which one is chosen at a given time. Consider adding an indication e.g. at the bottom of the center MFD which type of heading currently is selected.

**Comment by Rudolf339** [comment]
Since the details of function and how it should be irl is unknown, I would rather put the indication in a popup tooltip for the sake if authenticity

**Comment by 5H1N0B11** [comment]
In fact, there is already an indication on the center mfd : TRU or MAG. But when I started to work on the HUD, I had to move the head up and now you can't see it unless you move the pilot POV. Maybe the next work would be to implement the f16 way of moving the head.

**Comment by 5H1N0B11** [comment]
True heading : 
![image](https://user-images.githubusercontent.com/25423770/95927191-64bd3180-0dbe-11eb-83c5-ec4ecbb719c1.png)
Mag heading : 
![image](https://user-images.githubusercontent.com/25423770/95927245-81f20000-0dbe-11eb-954b-66dc0b4e2ddb.png)
I'll close the issue
