### ISSUE TITLE
Gear positions

### ISSUE THREAD

**Issue by Zaretto** [5H1N0B11/flightgear-mirage2000#80]
- Nose wheel in the air
- Main gear sunk into ground

The basic coordinates are correct so it is possibly the location of the masses that is wrong; although the model file could also need adjustment.

It should sit level on the runway - but a quick investigation showed unequal gear compression on the main gear

**Comment by AxelPaccalin** [comment]
In `Mirage2000-vsp.xml`

Nose contact point:
      <z>-1.518</z>
Rear contact point:
      <z>-1.458</z>

This could be as simple as that, however, we will have to cross-check with the gear meshes to be 100% sure.

**Comment by AxelPaccalin** [comment]
![Gears](https://user-images.githubusercontent.com/47812280/89159338-a1bfa900-d56f-11ea-9f28-3ba109ed650e.png)
The gears are indeed at the same vertical position  in `Models/m2000-5.ac`.

**Comment by paccalin** [comment]
The gear position is now synchronized with the ground position:
![Gears4](https://user-images.githubusercontent.com/1371865/89206409-8f6a5d00-d5b9-11ea-92e8-4c6b8745c7bd.png)

Fully extended (should only happen after takeoff):
![Gears4](https://user-images.githubusercontent.com/1371865/89206532-b6c12a00-d5b9-11ea-84b3-68a170fe9d55.png)

Fully compressed (should never happen):
![Gears5](https://user-images.githubusercontent.com/1371865/89206576-c50f4600-d5b9-11ea-89c8-1f45f8869d22.png)

Since we cannot set the maximum stroke of the damper in jsbsim, if you exceed maximum compression, the gear will go into the ground:
![Gears6](https://user-images.githubusercontent.com/1371865/89206706-f425b780-d5b9-11ea-979e-8dd11db2fbb2.png)

**Comment by paccalin** [comment]
Tested and tweaked with the new fuel system.

Compression for dry weight:
![GearsDRY](https://user-images.githubusercontent.com/1371865/89211741-7dd98300-d5c2-11ea-926e-b36c694acd99.png)

Compression for MTOW (16.5T: full fuel + full ventral):
![GearsMTOW](https://user-images.githubusercontent.com/1371865/89211785-977aca80-d5c2-11ea-9c4a-a7aa47012ab3.png)

**Comment by paccalin** [comment]
The horizontal adjustment of the wheel is not very precise, if someone know how to calculate precisely the `VRP` in `mirage2000-vsp.xml`, the whells will follow the ground more properly when rolling!

**Comment by Zaretto** [comment]
VRP is the matrix used to adjust from the 3d model to the JSBSim model, based on the origin of both.

After a quick check it appears that I didn't really check that the VRP was correct when I made the aero.

![image](https://user-images.githubusercontent.com/2045654/89405052-3dd9e380-d71b-11ea-8603-58ed38f31219.png)

VRP(x) should therefore be -1.726m; I haven't calculated the Z VRP.

Getting the tyres into exactly the right place can be tricky but firstly it is important to have the gear in the correct position in the JSBSim but also VRP(x,z) needs to be correct as otherwise the 3d models for the wheels will be in the wrong place when rendered.

**Comment by AxelPaccalin** [comment]
> VRP is the matrix used to adjust from the 3d model to the JSBSim model, based on the origin of both.
> 
> After a quick check it appears that I didn't really check that the VRP was correct when I made the aero.
> 
> ![image](https://user-images.githubusercontent.com/2045654/89405052-3dd9e380-d71b-11ea-8603-58ed38f31219.png)
> 
> VRP(x) should therefore be -1.726m; I haven't calculated the Z VRP.
> 
> Getting the tyres into exactly the right place can be tricky but firstly it is important to have the gear in the correct position in the JSBSim but also VRP(x,z) needs to be correct as otherwise the 3d models for the wheels will be in the wrong place when rendered.

Okay, I'll test with the new VRP(x) later in the day !

**Comment by AxelPaccalin** [comment]
According to the gear compression, this VRP value is incorrect. 
The eyeballed VRP value I found (which should be in the vicinity of the true value) was 290'' (7.366 meters).

**Comment by AxelPaccalin** [comment]
I think I figured that out ! (all following vectors are in the metric system).

Soo, if we consider the jsbsim main-gear contact point to be the "true/official" contact point for the MLG, the contact point is [8.76, ..., ...].

We know that the JSBSIM center of computation (AERORP) is [8.56, ..., ...].

We also know that the most bottom vertex of the wheel in the model is at [1.94771, ..., ...] relatively to the model origin.

So if my math is correct, to put the MLG vertex (of the model) on the MLG contact point (in JSBSIM) we need to have a bias translation of [6.812, 0, ?].

**Comment by Zaretto** [comment]
The 6.834 is the 3d model X origin measured from the nose; so calculated from the JSBSim offset using an offset -f -1.94771 will result at the same point.

**Comment by AxelPaccalin** [comment]
With the proper VRP, The gear now follows the ground even when the plane doesn't sit flat on the ground.
![GearsRotate](https://user-images.githubusercontent.com/47812280/89439456-852b9880-d74a-11ea-8d42-fe98500bdd86.png)
