### ISSUE TITLE
Nozzle has to be changed

### ISSUE THREAD

**Issue by Zaretto** [5H1N0B11/flightgear-mirage2000#84]
No idea what this means -Fabien can you explain.

**Comment by 5H1N0B11** [comment]
I mean the way the 3D model of the nozzle should react, depending on the n1/n2 and if there is after burner or not. it is just an adjustment on the 3D model I think

**Comment by Zaretto** [comment]
There is already a nozzle simulation as part of the 'extra'  engines simulation you will find in Systems/Mirage-2000-engines-Snecma-M53.xml

Main property is propulsion/engine[0]/alt/nozzle-pos-norm 

Also a 5 stage augmentation is modeled with a pressure distribution and lighting time - it's much the same as on the F-15 and a lot more realistic that the normal JSBSim augmenation model.

**Comment by 5H1N0B11** [comment]
I think this have been corrected. Thanks for your help @Zaretto
