### ISSUE TITLE
 Auto targeting

### ISSUE THREAD

**Issue by swampmo** [5H1N0B11/flightgear-mirage2000#9]
Radar auto targets any aircraft that flies in front of it and also auto targets its own missiles. This is bad for dogfight as you may shoot a wingman inadvertently  and waste missiles shooting down your own missiles. Suggestion, get with Nicoladis to see what he did with the OPRF version to fix this and key-bind "n" to select targets.

**Comment by NikolaiVChr** [comment]
Line 332 in radar2.nas should prevent you from targeting a missile. Not sure why it don't works:

if(type != "missile" and !contains(weaponRadarNames, type))

**Comment by 5H1N0B11** [comment]
is it fixed on the last mirage ?

**Comment by 5H1N0B11** [comment]
The mirage should not doing it anymore. The next changes with the new radar will be even better.
